### ISSUE TITLE
The main application freezes after loading a URL instead of an HTML page

### ISSUE THREAD

**Issue by zrfisaac** [salvadordf/WebUI4Delphi#1]
Hey, I've found what might be a bug when I open a URL instead of an HTML file like this : 
```pascal
procedure TMainForm.ShowBrowserBtnClick(Sender: TObject);
var
  LMyHTML : string;
begin
  if assigned(WebUI) then
  begin
    if (WebUI.IsAppRunning) then
    begin
      exit;
    end;
  end;

  LMyHTML := '<html><head><script src="webui.js"></script></head> Hello World ! </html>';
  FWindow := TWebUIWindow.Create;
  //FWindow.Show(LMyHTML);
  FWindow.Show('https://github.com/');
end;
```
And after I close the browser, the application freezes. Do you know what might be causing this? 

> I almost forgot to mention, I'm using Delphi XE2 on Windows 11

**Comment by salvadordf** [comment]
Hi,
WebUI requires that the web page loads the webui.js script to establish the communication between the desktop app and the web browser instance.

**Comment by zrfisaac** [comment]
Thanks!!!!! 😄

**Comment by zrfisaac** [comment]
Thanks!!!!! 😄
