### ISSUE TITLE
LoadLibrary failed on MacOS

### ISSUE THREAD

**Issue by aztack** [salvadordf/WebUI4Delphi#6]
I set a absolute dylib path to make sure it is exsits:
`WebUI.LibraryPath := '/Users/name/github/WebUI4Delphi/bin64/webui-2_debug.dylib'; `

But in following function
```
function TWebUI.LoadWebUILibrary: boolean;
...
FLibHandle := LoadLibrary(TempLibraryPath); // FLibHandle is 0

end;
```
FLibHandle is always zero.

**Comment by salvadordf** [comment]
In the case of MacOS applications the webui-2.dylib [dynamic library](https://developer.apple.com/documentation/xcode/embedding-nonstandard-code-structures-in-a-bundle) must be in the MyApplication.app/Contents/Frameworks directory.

**Comment by aztack** [comment]
> In the case of MacOS applications the webui-2.dylib [dynamic library](https://developer.apple.com/documentation/xcode/embedding-nonstandard-code-structures-in-a-bundle) must be in the MyApplication.app/Contents/Frameworks directory.

I also tried to place webui-2_debug.dylib and webui-2.dylib in above mentioned folder but got the same error:
<img width="216" alt="image" src="https://github.com/user-attachments/assets/4ee9566b-639e-44db-86a7-1b03657cb23b">

**Comment by aztack** [comment]
I tried to load dylib with LoadLibrary and inspect error with `GetLoadErrorStr` and found that the `webui-2.dylib` is of`Mach-O 64-bit dynamically linked shared library arm64` not x64 as expected. I change project target CPU to aarch64 and it works. (see https://github.com/webui-dev/webui/issues/482)

Maybe in `function TWebUI.LoadWebUILibrary : boolean;` you can use `GetLoadErrorStr` along with `GetLastOSError` to get more detailed error information

**Comment by salvadordf** [comment]
I just added the error information in TWebUI and the Minimal demo shows it if the initialization fails.
